# Generated by Django 2.2.3 on 2022-03-30 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_remove_appliedpromotion_promotion_rule'),
        ('promotions', '0002_auto_20190721_1836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromotionRule',
        ),
    ]
